### ISSUE TITLE
After upgrading nodev10 to 16 optional chaining is not working for template as well as in code

### ISSUE THREAD

**Issue by patelatit53** [JuniorTour/vue-template-babel-compiler#44]
**I recently tried to upgrade my node version as nodev10 stopped support,**

I had vue-template-babel-compiler installed to support optional chaining for the templates but after doing a fresh npm install, somehow I started getting Server compilation errors.

**Comment by JuniorTour** [comment]
Sorry for the late reply.


### 1. this lib do work for `Nuxt.js` && `Node.js v16+`
So this may be not related to Node version.

### 2. Many package version of your package.json  is not exist 

eg:
``` json
"@nuxtjs/pwa":"3.0.0–0",
"@nuxtjs/dotenv":"2.4.0",
```

So I can't finish the npm install process.

I think you may have the same issue, your npm install was not finished, so you get build error after `npm run dev`.

You may need clean up your npm dependencies.

You can refer to this nuxt DEMO project: https://github.com/JuniorTour/vue-template-babel-compiler-nuxt-project
